# theme: jekyll-theme-cayman
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: ./images/bio-photo-1.jpeg
# show_downloads: true
theme: jekyll-theme-minimal
title: "Yu Bao's Research Page"
description: "Research Scientist at ByteDance, specializing in LLM Alignment and Multimodal Modeling."
author: Yu Bao
